version: '3.1'
services:
  php-app:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./custom-apache-config.conf:/etc/apache2/sites-available/000-default.conf

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data:
